### ISSUE TITLE
프로젝트 초기 설정

### ISSUE THREAD

**Issue by Seok93** [Seok93/market-kurly-clone#1]
## Description
팀 프로젝트 작업 진행 전 환경 설정

## Todo List
- [x] Vite + React + Typescript 초기 환경 설정
- [x] Github Template 파일 추가
- [x] 라이브러리 추가
  - React-Router
  - React-Query
  - Recoil, Recoil-Persist
  - React-Hook-Form
  - StoryBook
  - Vitest, React-library-test
- [x] ESLint, Prettier 설정 추가
- [ ] Git Convention 정하기
- [ ] 파일 시스템 관리 구조 정하기

## Estimated Time
3시간 소요 예정
