### ISSUE TITLE
CSS Global, Variable, Reset 설정

### ISSUE THREAD

**Issue by Seok93** [Seok93/market-kurly-clone#11]
## Description
CSS 전역 설정, 변수 설정, 초기화 설정 추가

## Todo List
- [x] CSS 전역 설정
- [x] CSS 변수 설정
- [x] CSS 초기화(=reset) 설정

## Estimated Time
약 30분
