### ISSUE TITLE
Git 컨벤션, 파일 관리 구조, 라우팅 구조 정하기

### ISSUE THREAD

**Issue by Seok93** [Seok93/market-kurly-clone#3]
## Description
협업을 위해 git commit 컨벤션,  파일 관리 구조, 라우팅 구조를 정리하려고 한다.

## Todo List
- [x] Git Convention 정하기
- [x] 파일 시스템 관리 구조 정하기
- [x] 라우팅 구조 정하기

## Estimated Time
1~2시간

**Comment by Seok93** [comment]
# 📌Git Commit Convention
|타입 이름| 설명|
|:---|:---|
|Feat|새로운 기능 개발|
|Fix|버그 수정|
|Refactor|코드 리팩토링|
|Doc|문서 추가/수정|
|Design| CSS 등 사용자 UI 디자인 추가/수정|
|Style| 코드 포맷 변경, 세미콜론 누락, 코드 수정 없는 경우|
|Test| 테스트 코드|
|Rename|파일 or 디렉토리 수정하거나 옮기는 작업|
|Remove|파일 or 디렉토리 삭제하는 작업|
|Comment|필요한 주석 추가 및 변경|
|Chore|빌드 업무 수정, 패키지 매니저 수정, 패키지 관리자 구성 등 업데이트, Production Code 변경 없음|

---
# 📋 Commit Message 구조
commit message는 제목/본문/꼬리말로 구성한다.
```git
Type: [#IssueNumber-] Subject  // 제목

Body (선택사항)                 // 본문

Footer (선택사항)               // 꼬리말
```
`Type`: 어떤 의미로 커밋을 작성했는지 나타낸다. (ex. Feat, Fix, Refactor etc)
`Subject`: 커밋의 제목을 간략하게 작성
`Body`: 무엇을, 왜 변경했는지 상세한 내용을 작성
`Footer`: issue tracker id를 명시하고 싶은 경우에 작성

### 🪄제목
1. 제목은 1~2문장 이내로 작성한다. (50글자 이내)
2. 마침표 및 특수 기호는 사용하지 않는다.
3. 간결하고 요점을 중심으로 작성한다.
4. 명령조 / 행위를 중점으로 작성한다.

### 🪄 본문
1. 제목에 담을 수 없는 상세 설명이 필요할 때 작성한다.  (선택사항)
2. 어떻게보다 무엇을, 왜 변경했는지 상세하게 작성한다.
3. 제목과 구분하기 위해 공백 한 줄을 띄워서 작성한다.

### 🪄 꼬리말
1. issue tracker id를 명시하고 싶은 경우에 작성한다. (선택사항)
2. 유형: # 이슈 번호 형식으로 작성한다.
3. 여러 개의 이슈 번호는 쉼표로 구분한다.
4. 이슈 트래커 유형은 다음 중 하나를 사용한다.
  - Fixes: 이슈 수정중 (아직 해결되지 않는 경우)
  - Resolves: 이슈를 해결했을 때 사용
  - Ref: 참고할 이슈가 있을 때 사용
  - Related to: 해당 커밋에 관련된 이슈 번호 (아직 해결되지 않은 경)

---
# 🖥️ 사용 예시

```
Feat: 회원 가입 기능 구현

SMS, 이메일 중복확인 API 개발

Resolves: #123
Ref: #456
Related to: #48, #45
```

---
# 🔍 참고자료
1. [[Git] Commit Message Convention](https://velog.io/@archivvonjang/Git-Commit-Message-Convention)
6. [[Git] Commit Message Convention (협업을 위한 git 커밋컨벤션)](https://velog.io/@msung99/Git-Commit-Message-Convension)

**Comment by Seok93** [comment]
## 🔜라우팅 구조
![image](https://github.com/Seok93/market-kurly-clone/assets/32609010/85564000-2307-4175-b18d-d409adf3d744)

※ 차후 프로젝트 진행중 변경 가능성 有
