### ISSUE TITLE
Home 페이지 구현하기

### ISSUE THREAD

**Issue by Seok93** [Seok93/market-kurly-clone#8]
## Description
Home 페이지 만들기

## Todo List
- [ ] 특가, 혜택 등 상품을 보여주는 캐러셀 만들기
- [ ] 상품 상세 정보로 라우팅하기
- [ ] 더미 데이터 만들기

## Estimated Time
1~2일 예상
